PruebaDataSoft/Controllers/VehiculoController.cs
using ENTIDAD;
using NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PruebaDataSoft.Controllers
{
    public class VehiculoController : Controller
    {
        //Controlador de entidad de vehiculo
      
            // GET list de entidad de Vehiculo 
            public ActionResult Index()
            {
                var vhc = VehiculoCN.ListarVehiculo();
                return View(vhc);
            }

            // POST de entidad de Vehiculo 
            public ActionResult Crear()
            {
                return View();
            }
        [HttpPost]
        public ActionResult Crear(Vehiculo vhc)
        {
            try
            {
                if (vhc.Placa == null)
                {
                    ModelState.AddModelError("", "Debe escribir el número de placa..");
                    return View(vhc);
                }
                if (vhc.Dueño == null)
                {
                    ModelState.AddModelError("", "Debe escribir el nombre del dueño del vehiculo..");
                    return View(vhc);
                }
                if (vhc.Marca == null)
                {
                    ModelState.AddModelError("", "Debe escribir la marca del vehiculo..");
                    return View(vhc);
                }

                VehiculoCN.PostVehiculo(vhc);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Ocurriò el siguiente error: ", ex.Message);
                return View(vhc);
            }

        }

        // GET ID de entidad de Vehiculo 
        public ActionResult Detalle(int id)
        {
            var vhc = VehiculoCN.GetVehiculo(id);
            return View(vhc);
        }

        //PUT de entidad de Vehiculo
        public ActionResult Editar(int id)
        {
            var vhc = VehiculoCN.GetVehiculo(id);
            return View(vhc);
        }

        [HttpPost]
        public ActionResult Editar(Vehiculo vhc)
        {
            try
            {
                if (vhc.Placa == null)
                {
                    ModelState.AddModelError("", "Debe escribir el número de placa..");
                    return View(vhc);
                }
                if (vhc.Dueño == null)
                {
                    ModelState.AddModelError("", "Debe escribir el nombre del dueño del vehiculo..");
                    return View(vhc);
                }
                if (vhc.Marca == null)
                {
                    ModelState.AddModelError("", "Debe escribir la marca del vehiculo..");
                    return View(vhc);
                }
                VehiculoCN.PutVehiculo(vhc);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Ocurriò el siguiente error: ", ex.Message);
                return View(vhc);
            }

        }

        //DELETE de entidad de Vehiculo
        public ActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var vhc = VehiculoCN.GetVehiculo(id.Value);
            return View(vhc);
        }
        [HttpPost]
        public ActionResult Borrar(int id)
        {
            try
            {

                VehiculoCN.DeleteVehiculo(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Ocurriò el siguiente error: ", ex.Message);
                return View();
            }
        }

        //Asignar servicio a vehiculo
        public ActionResult AsignarServicio(int id)
        {
            var vhc = VehiculoCN.GetVehiculo(id);
            return View(vhc);
            
        }
        [HttpPost]
        public ActionResult AsignarServicio_Vehiculo(int servicioId, int vehiculoId)
        {
            try
            {
                VehiculoCN.AsignarServicio(servicioId, vehiculoId);
                return Json(new { ok = true, toRedirect = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

PruebaDataSoft/Views/Vehiculo/AsignarServicio.cshtml
@model ENTIDAD.Vehiculo

@{
    ViewBag.Title = "AsignarServicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("AsignarServicio_Vehiculo", "Vehiculo", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h2>Asignar Servicio</h2>
    <div>
        <h4>Vehiculo</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>

                @Html.DisplayNameFor(model => model.ID_Vehiculo)
            </dt>

            <dd>
                @Html.EditorFor(model => model.ID_Vehiculo, new { htmlAttributes = new { @disabled = "disabled", @id = "vehiculoId" } })
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Placa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Placa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Dueño)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Dueño)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Marca)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Marca)
            </dd>

        </dl>
    </div>
    <div class="form-horizontal">
        <div class="form-group">
            <p class="col-md-10">Seleccione el servicio</p>
            <div class="col-md-10">
                <select class="form-control" id="servicioId" name="servicioId">
                </select>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-3 col-md-4">
                <br />
                <button type="button" class="btn btn-primary btn-block" onclick="AsignarServicio()">
                    <i class="glyphicon glyphicon-floppy-save"></i>  Asignar servicio
                </button>
            </div>
        </div>
    </div>
    <p>
        @Html.ActionLink("Regresar", "Index")
    </p>

}
    @section scripts{
        <script>
            ListarServicios();
            function AsignarServicio() {
                var servicioId = $("#servicioId").val();
                var vehiculoId = $("#vehiculoId").val();
                servicioId = parseInt(servicioId);
                if (servicioId < 1 || vehiculoId < 1) {
                    alert("Debe escoger un servicio.");
                    return;
                }

                $.ajax({
                    url: "/Vehiculo/AsignarServicio_Vehiculo",
                    type: "post",
                    data: { servicioId, vehiculoId }
                }).done(function (response) {

                    if (response.ok) {
                        alert("Asignación creada correctamente.");
                        window.location = response.toRedirect;
                    }
                    else {
                        alert(response.msg);
                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {

                });
            }
        </script>
    }

PruebaDataSoft/Views/Vehiculo/Borrar.cshtml
@model ENTIDAD.Vehiculo

@{
    ViewBag.Title = "Borrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar vehiculo</h2>

<h3>Está seguro que desea borrar el vehiculo?</h3>
<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Vehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Vehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dueño)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dueño)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

    </dl>
    @using (Html.BeginForm("Borrar", "Vehiculo", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

PruebaDataSoft/Views/Vehiculo/Crear.cshtml
@model ENTIDAD.Vehiculo

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm("Crear", "Vehiculo", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Registrar vehiculo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dueño, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Dueño, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Dueño, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar vehiculo" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "Vehiculo")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PruebaDataSoft/Views/Vehiculo/Detalle.cshtml
@model ENTIDAD.Vehiculo

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle del vehiculo</h2>

<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Vehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Vehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dueño)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dueño)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar vehiculo", "Editar", new { id = Model.ID_Vehiculo }) |
    @Html.ActionLink("Regresar", "Index")
</p>

PruebaDataSoft/Views/Vehiculo/Editar.cshtml
@model ENTIDAD.Vehiculo

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm("Editar", "Vehiculo", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Vehiculo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_Vehiculo)
 

    <div class="form-group">
        @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Dueño, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Dueño, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Dueño, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PruebaDataSoft/Views/Vehiculo/Index.cshtml
@model IEnumerable<ENTIDAD.Vehiculo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vehiculos</h2>

<p>
    @Html.ActionLink("Agregar vehiculo", "Crear", "Vehiculo")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_Vehiculo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Placa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dueño)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>Asignación de servicio</th>
        <th>Herramientass</th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ID_Vehiculo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Placa)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Dueño)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Marca)
    </td>
    <td>
        @Html.ActionLink("Asignar servicio", "AsignarServicio", new { id = item.ID_Vehiculo })
    </td>
    <td>
        @Html.ActionLink("Editar", "Editar", new { id = item.ID_Vehiculo }) |
        @Html.ActionLink("Detalles", "Detalle", new { id = item.ID_Vehiculo }) |
        @Html.ActionLink("Borrar", "Borrar", new { id = item.ID_Vehiculo })
    </td>
</tr>
}

</table>