PruebaDataSoft/Controllers/ServicioController.cs
using ENTIDAD;
using NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PruebaDataSoft.Controllers
{
    //Controlador de entidad de servicios
    public class ServicioController : Controller
    {
        // GET list de entidad de Servicio 
        public ActionResult Index()
        {
            var srv = ServicioCN.ListarServicios();
            return View(srv);
        }

        // POST de entidad de Servicio 
        public ActionResult Crear () 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear (Servicios srv)
        {
            try
            {
                if (srv.Descripción ==null)
                {
                    ModelState.AddModelError("", "Debe escribir la descripción del servicio..");
                    return View(srv);
                }
                if (srv.Monto < 1)
                {
                    ModelState.AddModelError("", "Debe escribir un monto superior a 0");
                    return View(srv);
                }
                ServicioCN.PostServicio(srv);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Ocurriò el siguiente error: ", ex.Message);
                return View(srv);
            }
          
        }

        // GET ID de entidad de Servicio 
        public ActionResult Detalle(int id)
        {
            var srv = ServicioCN.GetServicio(id);
            return View(srv);
        }

        //PUT de entidad de Servicio
        public ActionResult Editar(int id)
        {
            var srv = ServicioCN.GetServicio(id);
            return View(srv);
        }

        [HttpPost]
        public ActionResult Editar(Servicios srv)
        {
            try
            {
                if (srv.Descripción == null)
                {
                    ModelState.AddModelError("", "Debe escribir la descripción del servicio..");
                    return View(srv);
                }
                if (srv.Monto <1)
                {
                    ModelState.AddModelError("", "Debe escribir un monto superior a 0");
                    return View(srv);
                }
                ServicioCN.PutServicio(srv);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Ocurriò el siguiente error: ", ex.Message);
                return View(srv);
            }

        }
        //DELETE de entidad de Servicio
        public ActionResult Borrar(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var srv = ServicioCN.GetServicio(id.Value);
            return View(srv);
        }
        [HttpPost]
        public ActionResult Borrar(int id)
        {
            try
            {
               
                ServicioCN.DeleteServicio(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Ocurriò el siguiente error: ", ex.Message);
                return View();
            }
        }

        //Lista en select de asinar servicio
        public JsonResult ListarServicios()
        {
            try
            {
                var lista = ServicioCN.ListarServicios();
                return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        //Lista de operaciones
        public ActionResult ListarOperaciones()
        {
            return View(ServicioCN.ListarOperaciones());
        }

    }
}

PruebaDataSoft/Views/Servicio/Borrar.cshtml
@model ENTIDAD.Servicios

@{
    ViewBag.Title = "Borrar servicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar servicio</h2>

<h3>Está seguro de eliminar el servicio?</h3>
<div>
    <h4>Servicio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Servicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Servicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripción)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripción)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto)
        </dd>

    </dl>

    @using (Html.BeginForm("Borrar","Servicio",FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

PruebaDataSoft/Views/Servicio/Crear.cshtml
@model ENTIDAD.Servicios

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear nuevo servicio</h2>


@using (Html.BeginForm("Crear", "Servicio", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Servicios</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   
        <div class="form-group">
            @Html.LabelFor(model => model.Descripción, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripción, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripción, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar Servicio" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "Servicio")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PruebaDataSoft/Views/Servicio/Detalle.cshtml
@model ENTIDAD.Servicios

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle del servicio</h2>

<div>
    <h4>Servicios</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_Servicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Servicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripción)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripción)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Monto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Monto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar servicio", "Editar", new {id = Model.ID_Servicio }) |
    @Html.ActionLink("Regresar", "Index")
</p>

PruebaDataSoft/Views/Servicio/Editar.cshtml
@model ENTIDAD.Servicios

@{
    ViewBag.Title = "Editar servicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar servicio</h2>


@using (Html.BeginForm("Editar","Servicio", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Servicio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model=> model.ID_Servicio)
  
        <div class="form-group">
            @Html.LabelFor(model => model.Descripción, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripción, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripción, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PruebaDataSoft/Views/Servicio/Index.cshtml
@model IEnumerable<ENTIDAD.Servicios>

@{
    ViewBag.Title = "Servicios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Servicios del lavacar</h2>

<p>
    @Html.ActionLink("Crear nuevo servicio", "Crear", "Servicio")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_Servicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripción)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monto)
        </th>
        <th>Listado de vehiculos</th>
        <th>Herramientass</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_Servicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripción)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Monto)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id = item.ID_Servicio }) |
            @Html.ActionLink("Detalles", "Detalle", new { id = item.ID_Servicio }) |
            @Html.ActionLink("Borrar", "Borrar", new { id = item.ID_Servicio })
        </td>
    </tr>
}

</table>

PruebaDataSoft/Views/Servicio/ListarOperaciones.cshtml
@model IEnumerable<ENTIDAD.OperacionesCE>

@{
    ViewBag.Title = "ListarOperaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Operaciones</h2>

<div class="form-horizontal">
    <div class="form-group">
        <p class="col-md-10">Seleccione el servicio</p>
        <div class="col-md-10">
            <select class="form-control sServicio" id="servicioId" name="servicioId"></select>
        </div>
    </div>

    <div class="form-group">
        <p class="col-md-10">Buscar dato</p>
        <div class="col-md-10">
            <input class="form-control" id="impBuscar" type="text" placeholder="Buscar..">
        </div>
    </div>
</div>
<table class="table table-striped table-sm" cellspacing="0" width="100%" id="tServicios">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Servicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vehiculo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dueño)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Placa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monto)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="trTabla">
            <td id="idServicio">
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td id="servicio">
                @Html.DisplayFor(modelItem => item.Servicio)
            </td>
            <td id="vehiculo">
                @Html.DisplayFor(modelItem => item.Vehiculo)
            </td>
            <td id="dueno">
                @Html.DisplayFor(modelItem => item.Dueño)
            </td>
            <td id="placa">
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td id="monto">
                @Html.DisplayFor(modelItem => item.Monto)
            </td>

        </tr>
    }

</table>
@section scripts{
    <script>
        ListarServicios();
    </script>
  
}